[package]
name = "grade_tracker"
version = "0.1.0"
authors = ["Brian Jiang <brianjiang2200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.x"
serde_json = "1.0.44"